// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateEventInput struct {
	Type string `json:"type"`
}

type CreateSessionInput struct {
	Config string `json:"config"`
}

type Event struct {
	ID string `json:"id"`
}

type Session struct {
	Token string `json:"token"`
}
